# Generated by Django 4.0.1 on 2022-02-23 01:43

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to=blog.models.file_path, verbose_name='Header Image'),
        ),
    ]
